### ISSUE TITLE
Parachutes not very distinctive

### ISSUE THREAD

**Issue by Gordon-Dry** [coldrifting/ExtraDockingPorts#1]
The tiny and small parachute parts have the same mass, same cost and many other values are the same, especially the ModuleParachute values.

**Comment by coldrifting** [comment]
Thanks, almost missed those when I was updating the docking port values. They should be fixed in version 1.0.3

**Comment by Gordon-Dry** [comment]
I guess that will be okay.

But one thing:
the order of the lines in the configs are just totally different than before, that makes it difficult to compare.

See this screenshot of a file comparision, it shows what I mean:
(left is 1.0.3 in GameData, right is 1.0.2 in archive)
![Screen-2022-01-11_01-49-24](https://user-images.githubusercontent.com/29145213/148862061-e5681629-f90d-47c7-8f72-ea0379385c75.png)

**Comment by coldrifting** [comment]
Ah, sorry about that. I was trying to group similar values together to make the config file easier to read.
