### ISSUE TITLE
CLS.cfg doesn't applay

### ISSUE THREAD

**Issue by MrAdskiy** [coldrifting/ExtraDockingPorts#3]
Hi, in my game CLS.cfg doesn't applay to ExtraDockingPorts. I wrote my patch which works.
[KSP.log](https://github.com/coldrifting/ExtraDockingPorts/files/9653392/KSP.log)
[ModuleManager.log](https://github.com/coldrifting/ExtraDockingPorts/files/9653398/ModuleManager.log)

**Comment by MrAdskiy** [comment]
I found a mistake. Parts ExtraDockingPorts doesn't have MODULE[ModuleDockingPort]

**Comment by MrAdskiy** [comment]
This is final version of changed patch which works.

[CLS_ExtraDockingPorts.txt](https://github.com/coldrifting/ExtraDockingPorts/files/9653753/CLS_ExtraDockingPorts.txt)

**Comment by coldrifting** [comment]
Thanks, I've updated the config to match the correct module name. I've left out the FINAL keyword, as that should only be used for personal patches. I'm closing this issue, but let me know if the issue hasn't been fixed and I'll reopen it.

**Comment by Grimmas** [comment]
Oops. Was sure I tested it but guess not. My bad, thanks for catching that! 👍🏻
